# Generated by Django 5.1.6 on 2026-04-21 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_manutencao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque_manutencao.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque_manutencao.user')),
            ],
        ),
    ]
