# Generated by Django 5.1.6 on 2026-06-05 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_manutencao', '0002_lista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='user',
        ),
        migrations.CreateModel(
            name='MaterialManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Material')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Especificação')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo no Almoxarifado')),
                ('quantidade_atual', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada (Compra/Abastecimento)'), ('S', 'Saída (Aplicação em Ordem de Manutenção)'), ('I', 'Inventário (Ajuste de Saldo)')], default='S', max_length=1, verbose_name='Tipo de Movimentação')),
                ('condicoes_pagamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condições de Pagamento / Nota Fiscal')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Movimentada')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque_manutencao.materialmanutencao')),
            ],
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.DeleteModel(
            name='Lista',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
