# Generated by Django 5.1.6 on 2026-06-10 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_manutencao', '0003_remove_lista_stream_remove_lista_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='condicoes_pagamento',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='aplicacao',
            field=models.CharField(default='', help_text='Onde o material foi aplicado ou motivo da entrada', max_length=255),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialmanutencao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialmanutencao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materialmanutencao',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='materialmanutencao',
            name='quantidade_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialmanutencao',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=12),
        ),
        migrations.AlterField(
            model_name='materialmanutencao',
            name='usuario_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Abastecimento)'), ('SAIDA', 'Saída (Baixa/Consumo)')], max_length=7),
        ),
    ]
